name: nymea-networkmanager
version: 0.1.0
summary: Daemon for setup wireless connection using Bluetooth LE. 
description: |
  The nymea-networkmanager daemon provides a Bluetooth Low Energy server and
  allows to configure the WiFi network by provisioning credentials from the
  smartphone to an embedded device via Bluetooth.
  Use BerryLan or nymea:app to remotely configure WiFi by connecting to
  "BT WLAN setup".

grade: stable
base: core18
confinement: strict

apps:
  nymea-networkmanager:
    command: env PATH=$PATH:$SNAP/bin qt5-launch nymea-networkmanager -a "BT WLAN setup" -m offline
    daemon: simple
    restart-condition: always
    plugs:
      - bluez
      - bluetooth-control
      - network-manager

parts:
  # nymea-networkmanager
  nymea-networkmanager:
    plugin: nil
    build-attributes: [keep-execstack]
    stage-packages:
      - nymea-networkmanager


  # Custom launcher to support also armhf
  qt5-launch:
    plugin: dump
    build-attributes: [keep-execstack]
    source: snap/
    organize:
      qt5-launch: bin/
